local list = {
    { name = "lua_ls", alone = false },
    { name = "clangd", alone = false },
    -- { name = "asm_lsp", alone = false },
    { name = "bashls", alone = false },
    { name = "cmake", alone = false },
    { name = "cssls", alone = false },
    { name = "dockerls", alone = false },
    { name = "emmet_ls", alone = false },
    { name = "gopls", alone = false },
    { name = "html", alone = false },
    { name = "jsonls", alone = false },
    { name = "rust_analyzer", alone = false },
    -- { name = "tsserver", alone = true },
    -- { name = "psalm", alone = false },
    -- { name = "powershell_es", alone = false },
    -- { name = "pyright", alone = false },
    -- { name = "jedi_language_server", alone = false },
    { name = "pylsp", alone = false },
    -- { name = "sqlls", alone = false }, -- need extra yaml configuration
    -- { name = "tailwindcss", alone = false },
    { name = "volar", alone = false }, -- Can be customized to override the default tsserver
    -- { name = "marksman", alone = false },
    { name = "vimls", alone = false },
    { name = "jsonls", alone = false },
    { name = "dockerls", alone = false },
    { name = "cssls", alone = false },
    -- { name = "hls", alone = false },
    -- { name = "vls", alone = false },
    -- { name = "kotlin_language_server", alone = false },
    -- { name = "nimls", alone = false },
    -- { name = "ocamllsp", alone = false },
    -- { name = "zls", alone = false },
    -- { name = "intelephense", alone = false },
    { name = "vtsls", alone = false },
    { name = "unocss", alone = false },
    { name = "yamlls", alone = false },
    { name = "lemminx", alone = false },
    { name = "taplo", alone = false },
}

return list
