--- @class LangSpec
--- @field opt table?
--- @field lsp string?
--- @field format string[]?
--- @field lint string[]?
--- @field others string[]?
--- @field before_set function?
--- @field after_set function?
--- @field plugins LazySpec[]?
