return
--- @type LazySpec
{
    {
        "HiPhish/rainbow-delimiters.nvim",
        event = "VeryLazy",
    },
    {
        "nvim-treesitter/nvim-treesitter",
        event = "VeryLazy",
        build = function()
            require("nvim-treesitter.install").update({ with_sync = true })()
        end,
        opts = {
            ensure_installed = {
                "c",
                "go",
                "lua",
                "vim",
                "vimdoc",
                "bash",
                "c_sharp",
                "cmake",
                "cpp",
                "comment",
                "css",
                "diff",
                "dockerfile",
                "git_config",
                "git_rebase",
                "gitattributes",
                "gitcommit",
                "gitignore",
                "gomod",
                "gosum",
                "gowork",
                "hjson",
                "html",
                "ini",
                "javascript",
                "json",
                "json5",
                "jsdoc",
                "jsonc",
                "luadoc",
                "luap",
                "make",
                "markdown",
                "meson",
                "ninja",
                "nix",
                "python",
                "pug",
                "rust",
                "scss",
                "sql",
                "svelte",
                "toml",
                "tsx",
                "typescript",
                "vue",
                "yaml",
                "zig",
            },
            auto_install = true,
            highlight = {
                enable = true,
                additional_vim_regex_highlighting = false,
            },
            indent = {
                enable = true,
            },
            incremental_selection = {
                enable = true,
                keymaps = {
                    init_selection = "<CR>",
                    node_incremental = "<CR>",
                    node_decremental = "<BS>",
                    scope_incremental = "<TAB>",
                },
            },
        },
    },
}
